### ISSUE TITLE
How to train from Mnist datasets?

### ISSUE THREAD

**Issue by Michi-123** [Lornatang/DCGAN-PyTorch#1]
Could you tell me how to train GAN model from Mnist datasets, on 'pip installed dcgan_pytorch'?

**Comment by Lornatang** [comment]
python3 main.py mnist  -g g-mnist -d d-mnist --gpu 0

**Comment by Michi-123** [comment]
Thanks.
Is it difficult to train on 'pip installed dcgan_pytorch'?
I mean, do I need to implement example code myself?

**Comment by Lornatang** [comment]
You can download my pre trained model directly and run `python3 main.py mnist -g g-mnist -d d-mnist --gpu 0 -e --pretrained`. Wait a min, See `imgs` folder.

**Comment by Michi-123** [comment]
I understand. Thank you.
